template = "https://github.com/giellalt/template-lang-und"
rev_id = 314
template_sha = "ad51f89a72714ab21c4272c003b7692c820e2b18"

[replacements]
__GLOTTOLOG_ID__ = "livv1243"
__REPO__ = "lang-olo"
__UND2C__ = "olo"
__UNDEFINED__ = "Livvi Karelian"
__UND__ = "olo"
