template = "https://github.com/giellalt/template-lang-und"
rev_id = 302
template_sha = "b3740681672fe3b348eb75d3170f7a2da900a0b1"

[replacements]
__GLOTTOLOG_ID__ = "livv1243"
__REPO__ = "lang-olo"
__UND2C__ = "olo"
__UNDEFINED__ = "Livvi Karelian"
__UND__ = "olo"
