theme: jekyll-theme-minimal
title: Livvi Karelian NLP Grammar
description:  Finite state and Constraint Grammar based analysers, proofing tools and language resources for the Livvi Karelian language 
plugins:
  - jemoji
  - jekyll-include-cache

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
